[package]
name = "poketrainers"
authors = ["beyond"]
version = "0.1.0"
edition = "2021"
description = "Display pokemon trainer sprites in your terminal."
license = "MIT"
readme = "README.md"
categories = ["command-line-interface", "command-line-utilities"]
keywords = ["pokemon", "trainers", "showdown", "terminal", "cli"]

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"

[dependencies]
clap = { version = "4.5.14", features = ["derive"] }
image = "0.25.8"
rand = "0.9.2"
rust-embed = "8.8.0"
showie = "2.0.1"